version: '3.8'
services:
    db:
        image: postgres
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
    
    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - db
    
    nest:
        image: node
        ports:
            - 3000:3000
        working_dir: /app
        command: npm run start:dev
        volumes:
            - .:/app

volumes:
    database: